# Generated by Django 5.2.7 on 2025-10-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
