# Generated by Django 5.2.7 on 2025-10-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_is_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='default', max_length=254, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
