# Generated by Django 5.2.7 on 2025-10-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
