# Generated by Django 5.2.7 on 2025-10-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
