# Generated by Django 5.2.7 on 2025-11-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_tutorship_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
